Check timestamp with tz
GIScience/ohsome-py pull request #132
Opened 2023-11-17 14:54 UTC by rp280

2023-11-17 16:26 UTC, SlowMo24 commented
I favour timestamps without time-zone. I never had a benefit only nuisance. For example you can note time zones differently (e.g. `z`== ` +00:00`, yet the ohsome api does not support all these notions. That is why we had to remove the `Z`in #127 

As you say: "everything is in UTC" so there is no benefit in marking that fact explicitly.

2023-11-22 11:07 UTC, rp280 commented
A Test for Issue #121 was also created in this Pull Request

2023-11-23 16:33 UTC, SlowMo24 requested changes
Nice progress. Please update the CHANGELOG and state explicitely that we are deviating from the ohsome api here

2023-11-23 16:33 UTC, SlowMo24 commented on ohsome/clients.py
> +        return _OhsomeClientContributionsAggregatedDensity(
please move these changes to the respective branch, then rebase on that branch. It is not a good idea to mix changes of different scope in one MR.

see #134

2023-11-23 16:33 UTC, SlowMo24 commented on ohsome/response.py
> +            features["@validFrom"] = features["@validFrom"].str.replace("Z", "")
move the str replacement within the other function, that would be cleaner

2023-11-23 16:33 UTC, SlowMo24 commented on ohsome/response.py
> +            result_df["fromTimestamp"] = result_df["fromTimestamp"].str.replace("Z", "")
same here and in all other occurences: move into function below

2023-11-23 16:33 UTC, SlowMo24 commented on ohsome/test/test_response.py
> +def test_contributions_count_density_groupbyboundary(base_client):
move this test to the respective branch (see above)

2023-11-29 14:30 UTC, SlowMo24 approved these changes

2023-11-29 14:32 UTC, merged